### ISSUE TITLE
Preview doesn't show some fields

### ISSUE THREAD

**Issue by msyriac** [simonsobs/productdb#1]
I created a new entry and the preview looks like this:
![Screenshot from 2022-02-07 10-10-53](https://user-images.githubusercontent.com/3674397/152815136-a87e98be-0e0c-4fb3-9ab2-a38ab9687398.png)

The fields "Date produced", "Produced by" and "Contact" don't seem to show in the preview even though they were entered.

I'm using Firefox 96.0.3 on Ubuntu 21.10.

**Comment by TaiSakuma** [comment]
That is true. Thank you for letting us know. We will look into it.

**Comment by TaiSakuma** [comment]
This problem has been fixed by the commit https://github.com/simonsobs/acondbw/commit/4af500ee81c11d8aaea1bbd516a55ad236e9270e. The fix has been deployed to the sites.

Please let me know if the same problem still occures.

**Comment by msyriac** [comment]
Looks good, thanks!
