### ISSUE TITLE
Editing the "paths" section of a post does not respect as-entered ordering

### ISSUE THREAD

**Issue by zatkins2** [simonsobs/productdb#2]
I am trying to edit this post by adding the paths indicated by the red arrows. When I operate in the "edit window," I insert each path in the location as indicated by the associated blue arrow, but after pressing submit, the ordering reverts back to what is shown in red.

![image](https://user-images.githubusercontent.com/46325652/153255520-c23d6d61-fde3-49fd-9afb-11f2d22991c3.png)
 
Firefox: 96.0.3
Windows 10 20H2 19042.1466

**Comment by TaiSakuma** [comment]
Thank you. Yes, that is what happens. In the current implementation, paths are an unordered set. It is not possible to reorder once they are entered into the database.

We have plans to make it possible to specify the order.
