### ISSUE TITLE
Feature suggestion:recommended products

### ISSUE THREAD

**Issue by msyriac** [simonsobs/productdb#3]
I'd like to request to add a feature that allows a product to have a ~"legacy"~ "recommended" flag, which would mean it is the most recent version. There can however be more than one recommended product in each "product type", since each product type might have a mix of different kinds of products. If a product has a ~"legacy"~ "recommended" flag, it could simply show up in the list with a slightly different background color (light pink?) and maybe a small label that says ~"legacy"~ "recommended". 

This will allow the most important products to stand out visually when someone opens up the productdb.

Open to thoughts from others like @mhasself and @aiolasimone on the details of the implementation, including the name ~"legacy"~ "recommended".

**Comment by mhasself** [comment]
Seems helpful.  If the goal is to help people find the latest or recommended thing, maybe the tag could be called "latest" or "recommended"?
 
I think "legacy" might be reasonably interpreted as "old" ("support for legacy hardware").

**Comment by msyriac** [comment]
That's a fair point. I suggest "recommended" for now.

**Comment by TaiSakuma** [comment]
Thank you for the suggestion.

This can be a tag when [tags](https://github.com/simonsobs/acondbw/issues/9) are implemented.

**Comment by msyriac** [comment]
Just bumping this up; we have very crowded product lists in ACT at the moment, and quickly have this in SO soon.  It's useful for people to know what is "recommended", and ideally these would be pinned to the top of the list in each category.

**Comment by TaiSakuma** [comment]
The plan is to implement this feature as tags. We have two open issues:

- https://github.com/simonsobs/acondbs/issues/45 (backend)
- https://github.com/simonsobs/acondbw/issues/9 (fontend)

It will be easier to work on the backend after upgrading SQLAlchemy to version 2.
- https://github.com/simonsobs/acondbs/issues/41

These issues are in the project ProductDB: https://github.com/orgs/simonsobs/projects/36/views/1
Each issue has a target date there.
