### ISSUE TITLE
Version field?

### ISSUE THREAD

**Issue by msyriac** [simonsobs/productdb#4]
Should we have a dedicated field for the version tag of a product? I don't like that I'm forced to add this to the product name. That can cause non-uniformity in where people specify the version. Also, I think such a version field should be mandatory, so that people are forced to version their products.
(Apologies if this is already implemented and I missed it!)

**Comment by TaiSakuma** [comment]
Thank you for the suggestion.

Yes, I have had a question about how products should be versioned. Version control can be implemented in many ways. A preferred way might be different for a different product type.

With regard to a dedicated field for the version, in the backend DB server, fields of products are customizable. Different product types can have different fields. When a web interface for customizing fields is developed, you will be able to add a version field and enter versions to the field.
