### ISSUE TITLE
Feature suggestion: email updates?

### ISSUE THREAD

**Issue by msyriac** [simonsobs/productdb#5]
In the past in ACT, we used to send emails to "ACT Pipeline" whenever a new product was released. Perhaps we could have an option to tie each productdb to an email address, and send an email whenever a new product is added (or optionally, also when updated). Thoughts @mhasself ?

**Comment by mhasself** [comment]
Something like this seems wise... perhaps Slack integration? ... doesn't require a source email account and an listserv.

**Comment by TaiSakuma** [comment]
Thank you for your suggestion. I made an [entry](https://github.com/simonsobs/acondbs/issues/32) in the [project](https://github.com/orgs/simonsobs/projects/4).
